import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ReactElement, useState } from "react";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

import { useTranslation } from "../hooks/myHooks";
import FHLayout from "../components/common/layouts/HFLayout";
import { useAppSelector } from "../hooks/redux";
import { userSlice } from "../store/reducers/UserSlice";
import { useDispatch } from "react-redux";
import HomeEntry from "../components/home/HomeEntry";

export default function Home() {
  const t = useTranslation();
  const [counter, setCounter] = useState(0);
  const handleClick = () => {
    setCounter(counter + 1);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HomeEntry />
      </main>
    </div>
  );
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <FHLayout>{page}</FHLayout>;
};
