import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ReactElement } from "react";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

import { useTranslation } from "../hooks/myHooks";
import Layout from "../components/layouts/Layout";

export default function Home() {
  const t = useTranslation();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>{t.homePage.title}</h1>
      </main>

      <footer className={styles.footer}>Мой футер</footer>
    </div>
  );
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};
